//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictEquipWeaponTypeEnum : int
{
    /// <summary>
    /// 剑
    /// </summary>
    sward = 0,
    /// <summary>
    /// 刀
    /// </summary>
    saber = 1,
    /// <summary>
    /// 抢
    /// </summary>
    gun = 2,
    /// <summary>
    /// 拳套
    /// </summary>
    boxing = 3,
    /// <summary>
    /// 法杖
    /// </summary>
    wand = 4,
    /// <summary>
    /// 弓箭
    /// </summary>
    bow = 5,
    /// <summary>
    /// 匕首
    /// </summary>
    dagger = 6,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 7,

}

public class DictEquipWeaponTypeEnumString
{
    /// <summary>
    /// 剑
    /// </summary>
    public const string sward = "sward";
    /// <summary>
    /// 刀
    /// </summary>
    public const string saber = "saber";
    /// <summary>
    /// 抢
    /// </summary>
    public const string gun = "gun";
    /// <summary>
    /// 拳套
    /// </summary>
    public const string boxing = "boxing";
    /// <summary>
    /// 法杖
    /// </summary>
    public const string wand = "wand";
    /// <summary>
    /// 弓箭
    /// </summary>
    public const string bow = "bow";
    /// <summary>
    /// 匕首
    /// </summary>
    public const string dagger = "dagger";

public static string[] vlas = new string[]{
		
"sward",

"saber",

"gun",

"boxing",

"wand",

"bow",

"dagger",
""
	};
}
