//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictEquipEquipTypeEnum : int
{
    /// <summary>
    /// 武器
    /// </summary>
    weapon = 0,
    /// <summary>
    /// 衣服
    /// </summary>
    dress = 1,
    /// <summary>
    /// 项链
    /// </summary>
    necklace = 2,
    /// <summary>
    /// 戒指
    /// </summary>
    ring = 3,
    /// <summary>
    /// 手镯
    /// </summary>
    hand = 4,
    /// <summary>
    /// 帽子
    /// </summary>
    hat = 5,
    /// <summary>
    /// 坐骑
    /// </summary>
    ride = 6,
    /// <summary>
    /// 翅膀
    /// </summary>
    wing = 7,
    /// <summary>
    /// 法宝
    /// </summary>
    magic_key = 8,
    /// <summary>
    /// 法宝配件1
    /// </summary>
    magic_key_left = 9,
    /// <summary>
    /// 法宝配件2
    /// </summary>
    magic_key_right = 10,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 11,

}

public class DictEquipEquipTypeEnumString
{
    /// <summary>
    /// 武器
    /// </summary>
    public const string weapon = "weapon";
    /// <summary>
    /// 衣服
    /// </summary>
    public const string dress = "dress";
    /// <summary>
    /// 项链
    /// </summary>
    public const string necklace = "necklace";
    /// <summary>
    /// 戒指
    /// </summary>
    public const string ring = "ring";
    /// <summary>
    /// 手镯
    /// </summary>
    public const string hand = "hand";
    /// <summary>
    /// 帽子
    /// </summary>
    public const string hat = "hat";
    /// <summary>
    /// 坐骑
    /// </summary>
    public const string ride = "ride";
    /// <summary>
    /// 翅膀
    /// </summary>
    public const string wing = "wing";
    /// <summary>
    /// 法宝
    /// </summary>
    public const string magic_key = "magic_key";
    /// <summary>
    /// 法宝配件1
    /// </summary>
    public const string magic_key_left = "magic_key_left";
    /// <summary>
    /// 法宝配件2
    /// </summary>
    public const string magic_key_right = "magic_key_right";

public static string[] vlas = new string[]{
		
"weapon",

"dress",

"necklace",

"ring",

"hand",

"hat",

"ride",

"wing",

"magic_key",

"magic_key_left",

"magic_key_right",
""
	};
}
