//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictClassEnum : int
{
    /// <summary>
    /// 玩家
    /// </summary>
    Player = 0,
    /// <summary>
    /// 英雄
    /// </summary>
    Hero = 1,
    /// <summary>
    /// 物品
    /// </summary>
    Goods = 2,
    /// <summary>
    /// 副本
    /// </summary>
    Fuben = 3,
    /// <summary>
    /// 时间
    /// </summary>
    DTime = 4,
    /// <summary>
    /// 关卡
    /// </summary>
    CopyLev = 5,
    /// <summary>
    /// 技能
    /// </summary>
    Skill = 6,
    /// <summary>
    /// Buff
    /// </summary>
    Buff = 7,
    /// <summary>
    /// 投射物
    /// </summary>
    Projectile = 8,
    /// <summary>
    /// 章节
    /// </summary>
    BigCopy = 9,
    /// <summary>
    /// 商店
    /// </summary>
    Shop = 10,
    /// <summary>
    /// 道具夺宝
    /// </summary>
    EquipCopy = 11,
    /// <summary>
    /// 限时宝藏
    /// </summary>
    GOLDCOPY = 12,
    /// <summary>
    /// 星期
    /// </summary>
    Week = 13,
    /// <summary>
    /// 黑市老大
    /// </summary>
    BlackMarket = 14,
    /// <summary>
    /// 神秘商店
    /// </summary>
    GoblinShop = 15,
    /// <summary>
    /// 远征商店
    /// </summary>
    YZShop = 16,
    /// <summary>
    /// 武道会商店
    /// </summary>
    PVPShop = 17,
    /// <summary>
    /// VIP功能
    /// </summary>
    VipOpenFunction = 18,
    /// <summary>
    /// PVP竞技场
    /// </summary>
    PVP = 19,
    /// <summary>
    /// 精英副本
    /// </summary>
    EliteCopy = 20,
    /// <summary>
    /// 燃烧远征
    /// </summary>
    LongCopy = 21,
    /// <summary>
    /// 普通副本
    /// </summary>
    NormalCopy = 22,
    /// <summary>
    /// 性别
    /// </summary>
    Sex = 23,
    /// <summary>
    /// 金字塔
    /// </summary>
    Mineral = 24,
    /// <summary>
    /// 分享
    /// </summary>
    Share = 25,
    /// <summary>
    /// 世界boss
    /// </summary>
    WorldBoss = 26,
    /// <summary>
    /// 世界boss商店
    /// </summary>
    WorldBossShop = 27,
    /// <summary>
    /// 武林大会商店
    /// </summary>
    WLShop = 28,
    /// <summary>
    /// 武林大会
    /// </summary>
    WLDH = 29,
    /// <summary>
    /// 活动时间
    /// </summary>
    ActivityTime = 30,
    /// <summary>
    /// 大闯关
    /// </summary>
    Breakthrough = 31,
    /// <summary>
    /// 专属
    /// </summary>
    Exclusive = 32,
    /// <summary>
    /// 奥义
    /// </summary>
    Mysteries = 33,
    /// <summary>
    /// 阵容选择
    /// </summary>
    ZhenRong = 34,
    /// <summary>
    /// 大闯关商店
    /// </summary>
    BreakthroughShop = 35,
    /// <summary>
    /// 奥义商店
    /// </summary>
    MysteriesShop = 36,
    /// <summary>
    /// 切磋战斗
    /// </summary>
    QieCuo = 37,
    /// <summary>
    /// 好友
    /// </summary>
    Friend = 38,
    /// <summary>
    /// 超级大奖
    /// </summary>
    SuperPrize = 39,
    /// <summary>
    /// vip商店
    /// </summary>
    VipShop = 40,
    /// <summary>
    /// 街霸汽车
    /// </summary>
    JieBaQiChe = 41,
    /// <summary>
    /// 掉金币
    /// </summary>
    DiaoJinBi = 42,
    /// <summary>
    /// 躲避环境
    /// </summary>
    DuoBiHuanJing = 43,
    /// <summary>
    /// 奇遇切磋
    /// </summary>
    QYQIECUO = 44,
    /// <summary>
    /// 登录任务
    /// </summary>
    Login = 45,
    /// <summary>
    /// 抽奖任务
    /// </summary>
    Gamble = 46,
    /// <summary>
    /// 英雄相关的任务
    /// </summary>
    HeroTask = 47,
    /// <summary>
    /// 障碍物
    /// </summary>
    OBSTRUCTION = 48,
    /// <summary>
    /// 战斗过程
    /// </summary>
    Battleing = 49,
    /// <summary>
    /// 岩浆副本
    /// </summary>
    YANJIANG_COPY = 50,
    /// <summary>
    /// 英雄商店
    /// </summary>
    HERO_SHOP = 51,
    /// <summary>
    /// 装备商店
    /// </summary>
    Equip_shop = 52,
    /// <summary>
    /// 祈愿副本
    /// </summary>
    Supplication = 53,
    /// <summary>
    /// 群雄逐鹿
    /// </summary>
    Pvp1v1 = 54,
    /// <summary>
    /// 聊天任务
    /// </summary>
    ChatTask = 55,
    /// <summary>
    /// 星阵任务
    /// </summary>
    XingzhenTask = 56,
    /// <summary>
    /// 公会任务
    /// </summary>
    UnionTask = 57,
    /// <summary>
    /// 公会商店
    /// </summary>
    GROUP_SHOP = 58,
    /// <summary>
    /// 公会BOSS副本
    /// </summary>
    UNION_BOSS_BATTLE = 59,
    /// <summary>
    /// 新手引导关卡
    /// </summary>
    NEW_GPS = 60,
    /// <summary>
    /// 星阵
    /// </summary>
    Star_Array = 61,
    /// <summary>
    /// 称号
    /// </summary>
    NEW_TITLE = 62,
    /// <summary>
    /// 消费任务
    /// </summary>
    ConsumeTask = 63,
    /// <summary>
    /// 充值任务
    /// </summary>
    RechargeTask = 64,
    /// <summary>
    /// UI页面
    /// </summary>
    Page = 65,
    /// <summary>
    /// 强化版世界BOSS
    /// </summary>
    EnHanceWorldBoss = 66,
    /// <summary>
    /// 英雄抽卡
    /// </summary>
    HERO_Lottery = 67,
    /// <summary>
    /// 装备抽卡
    /// </summary>
    Exclusive_Lottery = 68,
    /// <summary>
    /// 坐骑幻化
    /// </summary>
    RideCustume = 69,
    /// <summary>
    /// 坐骑
    /// </summary>
    Ride = 70,
    /// <summary>
    /// 组队副本
    /// </summary>
    MultiplayerCopy = 71,
    /// <summary>
    /// 人物列传副本
    /// </summary>
    BiographyCopy = 72,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 73,

}

public class DictClassEnumString
{
    /// <summary>
    /// 玩家
    /// </summary>
    public const string Player = "Player";
    /// <summary>
    /// 英雄
    /// </summary>
    public const string Hero = "Hero";
    /// <summary>
    /// 物品
    /// </summary>
    public const string Goods = "Goods";
    /// <summary>
    /// 副本
    /// </summary>
    public const string Fuben = "Fuben";
    /// <summary>
    /// 时间
    /// </summary>
    public const string DTime = "DTime";
    /// <summary>
    /// 关卡
    /// </summary>
    public const string CopyLev = "CopyLev";
    /// <summary>
    /// 技能
    /// </summary>
    public const string Skill = "Skill";
    /// <summary>
    /// Buff
    /// </summary>
    public const string Buff = "Buff";
    /// <summary>
    /// 投射物
    /// </summary>
    public const string Projectile = "Projectile";
    /// <summary>
    /// 章节
    /// </summary>
    public const string BigCopy = "BigCopy";
    /// <summary>
    /// 商店
    /// </summary>
    public const string Shop = "Shop";
    /// <summary>
    /// 道具夺宝
    /// </summary>
    public const string EquipCopy = "EquipCopy";
    /// <summary>
    /// 限时宝藏
    /// </summary>
    public const string GOLDCOPY = "GOLDCOPY";
    /// <summary>
    /// 星期
    /// </summary>
    public const string Week = "Week";
    /// <summary>
    /// 黑市老大
    /// </summary>
    public const string BlackMarket = "BlackMarket";
    /// <summary>
    /// 神秘商店
    /// </summary>
    public const string GoblinShop = "GoblinShop";
    /// <summary>
    /// 远征商店
    /// </summary>
    public const string YZShop = "YZShop";
    /// <summary>
    /// 武道会商店
    /// </summary>
    public const string PVPShop = "PVPShop";
    /// <summary>
    /// VIP功能
    /// </summary>
    public const string VipOpenFunction = "VipOpenFunction";
    /// <summary>
    /// PVP竞技场
    /// </summary>
    public const string PVP = "PVP";
    /// <summary>
    /// 精英副本
    /// </summary>
    public const string EliteCopy = "EliteCopy";
    /// <summary>
    /// 燃烧远征
    /// </summary>
    public const string LongCopy = "LongCopy";
    /// <summary>
    /// 普通副本
    /// </summary>
    public const string NormalCopy = "NormalCopy";
    /// <summary>
    /// 性别
    /// </summary>
    public const string Sex = "Sex";
    /// <summary>
    /// 金字塔
    /// </summary>
    public const string Mineral = "Mineral";
    /// <summary>
    /// 分享
    /// </summary>
    public const string Share = "Share";
    /// <summary>
    /// 世界boss
    /// </summary>
    public const string WorldBoss = "WorldBoss";
    /// <summary>
    /// 世界boss商店
    /// </summary>
    public const string WorldBossShop = "WorldBossShop";
    /// <summary>
    /// 武林大会商店
    /// </summary>
    public const string WLShop = "WLShop";
    /// <summary>
    /// 武林大会
    /// </summary>
    public const string WLDH = "WLDH";
    /// <summary>
    /// 活动时间
    /// </summary>
    public const string ActivityTime = "ActivityTime";
    /// <summary>
    /// 大闯关
    /// </summary>
    public const string Breakthrough = "Breakthrough";
    /// <summary>
    /// 专属
    /// </summary>
    public const string Exclusive = "Exclusive";
    /// <summary>
    /// 奥义
    /// </summary>
    public const string Mysteries = "Mysteries";
    /// <summary>
    /// 阵容选择
    /// </summary>
    public const string ZhenRong = "ZhenRong";
    /// <summary>
    /// 大闯关商店
    /// </summary>
    public const string BreakthroughShop = "BreakthroughShop";
    /// <summary>
    /// 奥义商店
    /// </summary>
    public const string MysteriesShop = "MysteriesShop";
    /// <summary>
    /// 切磋战斗
    /// </summary>
    public const string QieCuo = "QieCuo";
    /// <summary>
    /// 好友
    /// </summary>
    public const string Friend = "Friend";
    /// <summary>
    /// 超级大奖
    /// </summary>
    public const string SuperPrize = "SuperPrize";
    /// <summary>
    /// vip商店
    /// </summary>
    public const string VipShop = "VipShop";
    /// <summary>
    /// 街霸汽车
    /// </summary>
    public const string JieBaQiChe = "JieBaQiChe";
    /// <summary>
    /// 掉金币
    /// </summary>
    public const string DiaoJinBi = "DiaoJinBi";
    /// <summary>
    /// 躲避环境
    /// </summary>
    public const string DuoBiHuanJing = "DuoBiHuanJing";
    /// <summary>
    /// 奇遇切磋
    /// </summary>
    public const string QYQIECUO = "QYQIECUO";
    /// <summary>
    /// 登录任务
    /// </summary>
    public const string Login = "Login";
    /// <summary>
    /// 抽奖任务
    /// </summary>
    public const string Gamble = "Gamble";
    /// <summary>
    /// 英雄相关的任务
    /// </summary>
    public const string HeroTask = "HeroTask";
    /// <summary>
    /// 障碍物
    /// </summary>
    public const string OBSTRUCTION = "OBSTRUCTION";
    /// <summary>
    /// 战斗过程
    /// </summary>
    public const string Battleing = "Battleing";
    /// <summary>
    /// 岩浆副本
    /// </summary>
    public const string YANJIANG_COPY = "YANJIANG_COPY";
    /// <summary>
    /// 英雄商店
    /// </summary>
    public const string HERO_SHOP = "HERO_SHOP";
    /// <summary>
    /// 装备商店
    /// </summary>
    public const string Equip_shop = "Equip_shop";
    /// <summary>
    /// 祈愿副本
    /// </summary>
    public const string Supplication = "Supplication";
    /// <summary>
    /// 群雄逐鹿
    /// </summary>
    public const string Pvp1v1 = "Pvp1v1";
    /// <summary>
    /// 聊天任务
    /// </summary>
    public const string ChatTask = "ChatTask";
    /// <summary>
    /// 星阵任务
    /// </summary>
    public const string XingzhenTask = "XingzhenTask";
    /// <summary>
    /// 公会任务
    /// </summary>
    public const string UnionTask = "UnionTask";
    /// <summary>
    /// 公会商店
    /// </summary>
    public const string GROUP_SHOP = "GROUP_SHOP";
    /// <summary>
    /// 公会BOSS副本
    /// </summary>
    public const string UNION_BOSS_BATTLE = "UNION_BOSS_BATTLE";
    /// <summary>
    /// 新手引导关卡
    /// </summary>
    public const string NEW_GPS = "NEW_GPS";
    /// <summary>
    /// 星阵
    /// </summary>
    public const string Star_Array = "Star_Array";
    /// <summary>
    /// 称号
    /// </summary>
    public const string NEW_TITLE = "NEW_TITLE";
    /// <summary>
    /// 消费任务
    /// </summary>
    public const string ConsumeTask = "ConsumeTask";
    /// <summary>
    /// 充值任务
    /// </summary>
    public const string RechargeTask = "RechargeTask";
    /// <summary>
    /// UI页面
    /// </summary>
    public const string Page = "Page";
    /// <summary>
    /// 强化版世界BOSS
    /// </summary>
    public const string EnHanceWorldBoss = "EnHanceWorldBoss";
    /// <summary>
    /// 英雄抽卡
    /// </summary>
    public const string HERO_Lottery = "HERO_Lottery";
    /// <summary>
    /// 装备抽卡
    /// </summary>
    public const string Exclusive_Lottery = "Exclusive_Lottery";
    /// <summary>
    /// 坐骑幻化
    /// </summary>
    public const string RideCustume = "RideCustume";
    /// <summary>
    /// 坐骑
    /// </summary>
    public const string Ride = "Ride";
    /// <summary>
    /// 组队副本
    /// </summary>
    public const string MultiplayerCopy = "MultiplayerCopy";
    /// <summary>
    /// 人物列传副本
    /// </summary>
    public const string BiographyCopy = "BiographyCopy";

public static string[] vlas = new string[]{
		
"Player",

"Hero",

"Goods",

"Fuben",

"DTime",

"CopyLev",

"Skill",

"Buff",

"Projectile",

"BigCopy",

"Shop",

"EquipCopy",

"GOLDCOPY",

"Week",

"BlackMarket",

"GoblinShop",

"YZShop",

"PVPShop",

"VipOpenFunction",

"PVP",

"EliteCopy",

"LongCopy",

"NormalCopy",

"Sex",

"Mineral",

"Share",

"WorldBoss",

"WorldBossShop",

"WLShop",

"WLDH",

"ActivityTime",

"Breakthrough",

"Exclusive",

"Mysteries",

"ZhenRong",

"BreakthroughShop",

"MysteriesShop",

"QieCuo",

"Friend",

"SuperPrize",

"VipShop",

"JieBaQiChe",

"DiaoJinBi",

"DuoBiHuanJing",

"QYQIECUO",

"Login",

"Gamble",

"HeroTask",

"OBSTRUCTION",

"Battleing",

"YANJIANG_COPY",

"HERO_SHOP",

"Equip_shop",

"Supplication",

"Pvp1v1",

"ChatTask",

"XingzhenTask",

"UnionTask",

"GROUP_SHOP",

"UNION_BOSS_BATTLE",

"NEW_GPS",

"Star_Array",

"NEW_TITLE",

"ConsumeTask",

"RechargeTask",

"Page",

"EnHanceWorldBoss",

"HERO_Lottery",

"Exclusive_Lottery",

"RideCustume",

"Ride",

"MultiplayerCopy",

"BiographyCopy",
""
	};
}
