//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictAbilityPropEnum : int
{
    /// <summary>
    /// 伤害
    /// </summary>
    DMG = 1,
    /// <summary>
    /// 防御
    /// </summary>
    DEF = 2,
    /// <summary>
    /// 攻击
    /// </summary>
    ATK = 3,
    /// <summary>
    /// 当前血量
    /// </summary>
    HP = 4,
    /// <summary>
    /// 血量
    /// </summary>
    MAX_HP = 5,
    /// <summary>
    /// 血量回复
    /// </summary>
    HP_TREAT_SPEED = 6,
    /// <summary>
    /// 减伤
    /// </summary>
    REDUCDMG = 7,
    /// <summary>
    /// 暴击率
    /// </summary>
    CRIT = 8,
    /// <summary>
    /// 暴击伤害
    /// </summary>
    CRITDMG = 9,
    /// <summary>
    /// 格挡
    /// </summary>
    BLOC = 10,
    /// <summary>
    /// 格挡百分比
    /// </summary>
    BLOCPERCENT = 11,
    /// <summary>
    /// 命中
    /// </summary>
    EVAPERCENT = 12,
    /// <summary>
    /// 每秒输出
    /// </summary>
    DPS = 13,
    /// <summary>
    /// 攻击百分比
    /// </summary>
    ATKPERCENT = 14,
    /// <summary>
    /// 防御百分比
    /// </summary>
    DEFPERCENT = 15,
    /// <summary>
    /// 血量百分比
    /// </summary>
    HPMAXPERCENT = 16,
    /// <summary>
    /// 移动速度
    /// </summary>
    MOVESPEED = 17,
    /// <summary>
    /// 战斗速度
    /// </summary>
    BATTLESPEED = 18,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 19,

}

public class DictAbilityPropEnumString
{
    /// <summary>
    /// 伤害
    /// </summary>
    public const string DMG = "DMG";
    /// <summary>
    /// 防御
    /// </summary>
    public const string DEF = "DEF";
    /// <summary>
    /// 攻击
    /// </summary>
    public const string ATK = "ATK";
    /// <summary>
    /// 当前血量
    /// </summary>
    public const string HP = "HP";
    /// <summary>
    /// 血量
    /// </summary>
    public const string MAX_HP = "MAX_HP";
    /// <summary>
    /// 血量回复
    /// </summary>
    public const string HP_TREAT_SPEED = "HP_TREAT_SPEED";
    /// <summary>
    /// 减伤
    /// </summary>
    public const string REDUCDMG = "REDUCDMG";
    /// <summary>
    /// 暴击率
    /// </summary>
    public const string CRIT = "CRIT";
    /// <summary>
    /// 暴击伤害
    /// </summary>
    public const string CRITDMG = "CRITDMG";
    /// <summary>
    /// 格挡
    /// </summary>
    public const string BLOC = "BLOC";
    /// <summary>
    /// 格挡百分比
    /// </summary>
    public const string BLOCPERCENT = "BLOCPERCENT";
    /// <summary>
    /// 命中
    /// </summary>
    public const string EVAPERCENT = "EVAPERCENT";
    /// <summary>
    /// 每秒输出
    /// </summary>
    public const string DPS = "DPS";
    /// <summary>
    /// 攻击百分比
    /// </summary>
    public const string ATKPERCENT = "ATKPERCENT";
    /// <summary>
    /// 防御百分比
    /// </summary>
    public const string DEFPERCENT = "DEFPERCENT";
    /// <summary>
    /// 血量百分比
    /// </summary>
    public const string HPMAXPERCENT = "HPMAXPERCENT";
    /// <summary>
    /// 移动速度
    /// </summary>
    public const string MOVESPEED = "MOVESPEED";
    /// <summary>
    /// 战斗速度
    /// </summary>
    public const string BATTLESPEED = "BATTLESPEED";

public static string[] vlas = new string[]{
		
"DMG",

"DEF",

"ATK",

"HP",

"MAX_HP",

"HP_TREAT_SPEED",

"REDUCDMG",

"CRIT",

"CRITDMG",

"BLOC",

"BLOCPERCENT",

"EVAPERCENT",

"DPS",

"ATKPERCENT",

"DEFPERCENT",

"HPMAXPERCENT",

"MOVESPEED",

"BATTLESPEED",
""
	};
}
