//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public enum DictPlayerPropEnum : int
{
    /// <summary>
    /// 金币
    /// </summary>
    coin = 1,
    /// <summary>
    /// 保底石
    /// </summary>
    Guaranteedstone = 2,
    /// <summary>
    /// 初级幸运石
    /// </summary>
    Luckstone1 = 3,
    /// <summary>
    /// 中级幸运石
    /// </summary>
    Luckstone2 = 4,
    /// <summary>
    /// 高级幸运石
    /// </summary>
    Luckstone3 = 5,
    /// <summary>
    /// 五彩碎片
    /// </summary>
    wucai_suipian = 6,
    /// <summary>
    /// 电-五彩石
    /// </summary>
    wucai_yello = 7,
    /// <summary>
    /// 火-五彩石
    /// </summary>
    wucai_green = 8,
    /// <summary>
    /// 冰-五彩石
    /// </summary>
    wucai_blue = 9,
    /// <summary>
    /// 岩-五彩石
    /// </summary>
    wucai_zise = 10,
    /// <summary>
    /// 风-五彩石
    /// </summary>
    wucai_white = 11,
    /// <summary>
    /// 最大值
    /// </summary>
    MAX_COUNT = 12,

}

public class DictPlayerPropEnumString
{
    /// <summary>
    /// 金币
    /// </summary>
    public const string coin = "coin";
    /// <summary>
    /// 保底石
    /// </summary>
    public const string Guaranteedstone = "Guaranteedstone";
    /// <summary>
    /// 初级幸运石
    /// </summary>
    public const string Luckstone1 = "Luckstone1";
    /// <summary>
    /// 中级幸运石
    /// </summary>
    public const string Luckstone2 = "Luckstone2";
    /// <summary>
    /// 高级幸运石
    /// </summary>
    public const string Luckstone3 = "Luckstone3";
    /// <summary>
    /// 五彩碎片
    /// </summary>
    public const string wucai_suipian = "wucai_suipian";
    /// <summary>
    /// 电-五彩石
    /// </summary>
    public const string wucai_yello = "wucai_yello";
    /// <summary>
    /// 火-五彩石
    /// </summary>
    public const string wucai_green = "wucai_green";
    /// <summary>
    /// 冰-五彩石
    /// </summary>
    public const string wucai_blue = "wucai_blue";
    /// <summary>
    /// 岩-五彩石
    /// </summary>
    public const string wucai_zise = "wucai_zise";
    /// <summary>
    /// 风-五彩石
    /// </summary>
    public const string wucai_white = "wucai_white";

public static string[] vlas = new string[]{
		
"coin",

"Guaranteedstone",

"Luckstone1",

"Luckstone2",

"Luckstone3",

"wucai_suipian",

"wucai_yello",

"wucai_green",

"wucai_blue",

"wucai_zise",

"wucai_white",
""
	};
}
