//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictEquipEquipType
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// classId
        /// </summary>
        public XorInt classId_xor;
     /// <summary>
        /// classId
        /// </summary>
        public int classId{
            get{
                return classId_xor.val;
            }
        }
     /// <summary>
        /// classId
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// classId
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// classId
        /// </summary>
        public string typeName;
     /// <summary>
        /// 属性描述
        /// </summary>
        public List<string> extraEntrys;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int classId)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictEquipEquipType m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(classId))
            {
                return m_dict[classId];
            }
            else
            {
                Debug.LogError ("error id:"+classId);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_equip_equip_type.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.classId_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["classId"]]),fileReader.randomUtil);
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.typeName = DictTypeConvert.ParseString(str[fileReader.typeName2Index["typeName"]]);
            model.extraEntrys = DictTypeConvert.ParseArrayString(str[fileReader.typeName2Index["extraEntrys"]]);

            if (m_dict.ContainsKey(model.classId) == false)
            {
                m_dict.Add(model.classId, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictEquipEquipType Parse:Same Key = " + model.classId);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
