//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Xor;

public partial class DictEquipQulity
{

    // data model
    // [System.Serializable]
    public class Model
    {
     /// <summary>
        /// 装备ID
        /// </summary>
        public XorInt id_xor;
     /// <summary>
        /// 装备ID
        /// </summary>
        public int id{
            get{
                return id_xor.val;
            }
        }
     /// <summary>
        /// 品质
        /// </summary>
        public XorInt qulity_xor;
     /// <summary>
        /// 品质
        /// </summary>
        public int qulity{
            get{
                return qulity_xor.val;
            }
        }
     /// <summary>
        /// 物品名称
        /// </summary>
        public XorInt equip_type_xor;
     /// <summary>
        /// 物品名称
        /// </summary>
        public int equip_type{
            get{
                return equip_type_xor.val;
            }
        }
     /// <summary>
        /// 额外属性数量
        /// </summary>
        public XorInt extraAbilityNum_xor;
     /// <summary>
        /// 额外属性数量
        /// </summary>
        public int extraAbilityNum{
            get{
                return extraAbilityNum_xor.val;
            }
        }
     /// <summary>
        /// 品质随机系数
        /// </summary>
        public XorDouble qualityCoefficient_xor;
     /// <summary>
        /// 品质随机系数
        /// </summary>
        public double qualityCoefficient{
            get{
                return qualityCoefficient_xor.val;
            }
        }
     /// <summary>
        /// 品質名稱
        /// </summary>
        public string qulityName;

    public virtual Model Clone()
    {
        Model mm = this.MemberwiseClone() as Model;
        return mm;
    }
}

    //
    private Dictionary<int, Model> m_dict;

    // Get The Dictionary
    public Dictionary<int, Model> Dict
    {
        get
        {
            return m_dict;
        }
    }

    private List<Model> m_list;
	public List<Model> getList()
	{
		return m_list;
	}

    // Get The Model By Key
    public Model GetModel(int id)
    {
        if (m_dict == null)
        {
            Debug.LogError("DictEquipQulity m_dict Is Null");
            return null;
        }
        else
        {
            if (m_dict.ContainsKey(id))
            {
                return m_dict[id];
            }
            else
            {
                Debug.LogError ("error id:"+id);
                return null;
            }
        }
    }

    private DictString_LoadFinishedCallBack m_loadFinishedCallBack;
    // load the json file
    public void Load(string path,DictString_LoadFinishedCallBack callBack)
    {
        m_loadFinishedCallBack = callBack;

        //
        string filePath = path;
        if(!filePath.EndsWith("/"))
        {
            filePath += "/";
        }

        filePath += GetFileName();
        DictFileReader fileReader = new DictFileReader(filePath, DoParse);
    }

    // get file name
    public string GetFileName()
    {
        return "dict_equip_qulity.txt";
    }

    // parse the json data
    private void DoParse(DictFileReader fileReader)
    {
        m_dict = new Dictionary<int,Model>();
        m_list = new List<Model>();
        //
        do
        {
            string[] str = fileReader.ReadRow();
            if (str == null || str.Length == 0)
            {
                break;
            }

            //
            Model model = new Model();
            model.id_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["id"]]),fileReader.randomUtil);
            model.qulity_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["qulity"]]),fileReader.randomUtil);
            model.equip_type_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["equip_type"]]),fileReader.randomUtil);
            model.extraAbilityNum_xor = new XorInt( DictTypeConvert.ParseInt(str[fileReader.typeName2Index["extraAbilityNum"]]),fileReader.randomUtil);
            model.qualityCoefficient_xor = new XorDouble(DictTypeConvert.ParseDouble(str[fileReader.typeName2Index["qualityCoefficient"]]),fileReader.randomUtil);
            model.qulityName = DictTypeConvert.ParseString(str[fileReader.typeName2Index["qulityName"]]);

            if (m_dict.ContainsKey(model.id) == false)
            {
                m_dict.Add(model.id, model);
                m_list.Add(model);
            }
            else
            {
                Debug.LogError("DictEquipQulity Parse:Same Key = " + model.id);
            }

        } while (true);

        if(m_loadFinishedCallBack != null)
        {
            m_loadFinishedCallBack(GetFileName());
        }
    }

}
